config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :users

  resources :carousels

  root :to => 'welcome#index'

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
	belongs_to :user

	after_create :fetch_details



	def fetch_details
		self.send("fetch_details_from_#{self.provider.downcase}")
	end


	def fetch_details_from_facebook
		graph = Koala::Facebook::API.new(self.token)
		facebook_data = graph.get_object("me")
		self.username = facebook_data['username']
		self.save
	end

	def fetch_details_from_twitter

	end


	def fetch_details_from_github
	end


	def fetch_details_from_linkedin

	end

	def fetch_details_from_google_oauth2

	end
end

app/models/carousel.rb
class Carousel < ActiveRecord::Base
  validates :title, presence: true,
                    uniqueness: true,
                    length: { in: 3..50 }

  scope :order_by_id,  -> { order(:id) }
  scope :only_visible, -> { where(visible: true) }

  #Tells rails to use this uploader for this model.
  mount_uploader :image, ImageUploader   
end

app/models/identity.rb
class Identity < ActiveRecord::Base

  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :trackable, :validatable, :omniauthable
      
  validates_presence_of :email
  mount_uploader :image, ImageUploader
  has_many :authorizations, dependent: :destroy

  def self.new_with_session(params,session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"],without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.from_omniauth(auth, current_user)
    authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s, :token => auth.credentials.token, :secret => auth.credentials.secret).first_or_initialize
    if authorization.user.blank?
      user = current_user.nil? ? User.where('email = ?', auth["info"]["email"]).first : current_user
      if user.blank?
       user = User.new
       user.password = Devise.friendly_token[0,10]
       user.name = auth.info.name
       user.email = auth.info.email
       auth.provider == "twitter" ?  user.save(:validate => false) :  user.save
     end
     authorization.username = auth.info.nickname
     authorization.user_id = user.id
     authorization.save
   end
   authorization.user
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carousels_controller.rb
class CarouselsController < ApplicationController
  
  def index
    @carousels = Carousel.all.order_by_id

    respond_to do |format|
      format.html { render "index" }
    end
  end

  def show
    @carousel = load_carousel

    respond_to do |format|
      format.html { render "show" }
    end
  end

  def new
    @carousel = Carousel.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @carousel = load_carousel

    respond_to do |format|
      format.html
    end
  end

  def create
    @carousel = Carousel.new(carousel_params)

    respond_to do |format|
      if @carousel.save
        format.html { redirect_to carousels_path, notice: "Saccessful create" }
        format.json { render :index, status: :created, location: @carousel }
      else
        format.html { render :new }
        format.json { render json: @carousel.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @carousel = load_carousel

    respond_to do |format|
      if @carousel.update(carousel_params)
        format.html { redirect_to carousels_path, notice: 'Successful update' }
        format.json { render :index, status: :ok, location: @carousel }
      else
        format.html { render :edit }
        format.json { render json: @carousel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @carousel = load_carousel

    if @carousel.destroy
      redirect_to carousels_url, notice: ' Successful destroyed'
    else 
      flash[:alert] = 'Error destroyed'
      render :show
    end      
  end

  private
    def load_carousel
      Carousel.find(params[:id])
    end

    def carousel_params
      params.require(:carousel).permit(:title, :caption, :image, :visible, :promotion)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

	skip_before_filter :authenticate_user!
	def all
		p env["omniauth.auth"]
		user = User.from_omniauth(env["omniauth.auth"], current_user)
		if user.persisted?
			flash[:notice] = "You are in..!!! Go to edit profile to see the status for the accounts"
			sign_in_and_redirect(user)
		else
			session["devise.user_attributes"] = user.attributes
			redirect_to new_user_registration_url
		end
	end

	  def failure
      #handle you logic here..
      #and delegate to super.
      super
   end


	alias_method :facebook, :all
	alias_method :twitter, :all
	alias_method :linkedin, :all
	alias_method :github, :all
	alias_method :passthru, :all
	alias_method :google_oauth2, :all
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_user, only: [:show, :edit, :update]
  before_filter :validate_authorization_for_user, only: [:edit, :update]

  # GET /users
  def index
    @users = User.all
  end



  # GET /users/1
  def show
  end

  # GET /users/1/edit
  def edit
  end


  # PATCH/PUT /users/1
  def update
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def validate_authorization_for_user
       redirect_to root_path unless @user == current_user
    end

  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @carousels = Carousel.only_visible.order_by_id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carousels_helper.rb
module CarouselsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/carousels/_form.html.erb
<%= form_for @carousel, :html => { :class => "form-horizontal carousel" } do |f| %>

  <% if @carousel.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@carousel.errors.count, "error") %> prohibited this carousel from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @carousel.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>


    <div class="row control-group">
      <%= f.label :title, :class => "control-label col-sm-3" %>
      <div class="controls col-sm-7">
        <%= f.text_field :title, autofocus: true, :class => "form-control", placeholder: 'Tytuł strony' %>
        <small class="help-block">Ten tytuł jest wyświetlany dużą czcionką</small>
      </div>
    </div><br>

    <div class="row control-group">
    <%= f.label :caption, :class => "control-label col-sm-3" %>
      <div class="controls col-sm-7">
        <%= f.text_area :caption, :rows => 3, :cols => 250, :class => "form-control", placeholder: 'Treść wyświetlana na zdjęciu' %>
        <small class="help-block">Długi opis umieszczony poniżej tytułu. Może składać się z kilku wierszy</small>
      </div>
    </div><br>


    <div class="row control-group">
      <%= f.label :image, :class => "control-label col-sm-3" %>
      <div class="controls col-sm-7">               
        <%= image_tag(@carousel.image, size: "300x100", :class => "img-thumbnail img-responsive") if @carousel.image? %><br> 
        <%= @carousel.image_identifier if @carousel.image? %><br>
        <%= f.file_field :image, :class => "form-control" %>
        <small class="help-block">Najlepiej, gdy zdjęcie jest w rozdzielczości 1500x500</small>
      </div>
    </div><br>


    <div class="row control-group">
      <%= f.label :promotion, :class => "control-label col-sm-3" %>
      <div class="controls col-sm-7">
        <%= f.check_box :promotion, { checked_value: true, unchecked_value: false }  %>
        <small class="help-block">Zaznacz jeżeli slajd ma być wyświatlany nietypowo, jako promocja</small>
      </div>
    </div><br>

    <div class="row control-group">
      <%= f.label :visible, :class => "control-label col-sm-3" %>
      <div class="controls col-sm-7">
        <%= f.check_box :visible, { checked_value: true, unchecked_value: false }  %>
        <small class="help-block">Zaznacz jeżeli ma być wyświetlany ten slajd</small>
      </div>
    </div><br>

    <div class="row">
      <div class="col-sm-7 col-sm-offset-3">
        <%= f.submit :class => "btn btn-primary" %>
        <%= link_to 'Back', :back, :class => "btn btn-default" %>
      </div>
    </div>

<% end %>

<div id="lightbox" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <button type="button" class="close hidden" data-dismiss="modal" aria-hidden="true">×</button>
    <div class="modal-content">
      <div class="modal-body">
        <img src="" alt="" />
      </div>
    </div>
  </div>
</div>

app/views/carousels/edit.html.erb
<div class="mydata">
  <div class="container">
    <p class="lead text-center">Edycja slajdu</p>

    <%= render 'form' %>

  </div>
</div>

app/views/carousels/index.html.erb
<div class="mydata">
  <div class="container">
    <p class="lead text-center">Lista slajdów</p>

    <table class="table table-hover">
       <tbody>
        <% @carousels.each do |carousel| %>
          <tr>
            <td>
              <a href="#" class="thumbnail" data-toggle="modal" data-target="#lightbox"> 
                <%= image_tag(carousel.image, size: "300x100", :class => "image img-responsive") %>
              </a>
            </td>

            <td><strong><%= carousel.title %></strong><br>
                <%= carousel.caption %></td>

              <% if carousel.promotion? %>
                <td><span class="glyphicon glyphicon-ok"></span><br>
              <% else %>
                <td><span class="glyphicon glyphicon-remove"></span><br>
              <% end %>

              <% if carousel.visible? %>
                <span class="glyphicon glyphicon-ok"></span></td>
              <% else %>
                <span class="glyphicon glyphicon-remove"></span></td>
              <% end %>
            <td>
              <%= link_to ' ', edit_carousel_path(carousel), 
                  :class => "glyphicon glyphicon-edit", title: 'Edycja', rel: 'tooltip' %>

              <%= link_to ' ', carousel_path(carousel), method: :delete, data: { confirm: 'Are you sure?' }, 
                  :class => "glyphicon glyphicon-trash", title: 'Usuń', rel: 'tooltip' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to ' Dodaj slajd', new_carousel_path, 
                :class => "btn btn-primary glyphicon glyphicon-star-empty pull-right" %>

  </div>
</div>

<div id="lightbox" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <button type="button" class="close hidden" data-dismiss="modal" aria-hidden="true">×</button>
    <div class="modal-content">
      <div class="modal-body">
        <img src="" alt="" />
      </div>
    </div>
  </div>
</div>

app/views/carousels/new.html.erb
<div class="mydata">
  <div class="container">
    <p class="lead text-center">Nowy slajd</p>

    <%= render 'form' %>

  </div>
</div>

app/views/carousels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @carousel.title %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @carousel.caption %>
</p>

<p>
  <strong>Image:</strong>
  <%= @carousel.image %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @carousel.visible %>
</p>

<p>
  <strong>Promotion:</strong>
  <%= @carousel.promotion %>
</p>

<%= link_to 'Edit', edit_carousel_path(@carousel) %> |
<%= link_to 'Back', carousels_path %>

app/views/layouts/_footer.html.erb
<div id="myfooter">
  <div class="col-lg-4">
    <address>
      <strong>Monia&Ola, Inc.</strong><br>
      XX-XXX Bydgoszcz, ul. Jakaś 15<br>
      tel. +48 601-602-603<br>
      tel. +48 601-602-604<br>
      <a href="mailto:#">first.last@example.com</a>
    </address>
  </div><!-- /.col-lg-4 -->

  <div class="col-lg-4">
    <p>
      mBank S.A.<br>
      44 1140 2004 0000 3802 3134 5925<br>
    </p>
    <p>
      KRS: 016-917<br>
      NIP: 953-23-86-625<br>
    </p>

  </div><!-- /.col-lg-4 -->

  <div class="col-lg-4">
    <p>
      <%= image_tag("Facebook.png", alt: "") %>
      <div
        class="fb-like"
        data-share="true"
        data-width="450"
        data-show-faces="true">
      </div>
    </p>
    <p>&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </div><!-- /.col-lg-4 -->
</div><!-- /.myfooter -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar-wrapper">
  <div class="container">

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Letters</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Konfiguracja', carousels_path %></li>
            <li><%= link_to 'Użytkownicy', users_path %></li>
            <li><a href="#myfooter">Kontakt</a></li>
          </ul>


        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to current_user.name, current_user %></li>
          <li><%= link_to "Logout", destroy_user_session_path %></li>
          <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>


        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : t('Letters', default: t("breadcrumbs.application.title")) %></title>
    <%= stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true  %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%#= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%#= javascript_include_tag "application" %>

  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>


      <%= render 'layouts/messages' %>
      <%= yield %>


    <footer>
      <%= render 'layouts/footer' %>
    </footer>
 
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>


    <div class="row control-group">
      <%= f.label :name, :class => "control-label col-sm-3" %>
      <div class="controls col-sm-7">
        <%= f.text_field :name, autofocus: true, :class => "form-control", placeholder: 'Nazwa użytkownika' %>
        <small class="help-block">Wprowadź/zaktualizuj swoją nazwę</small>
      </div>
    </div><br>


    <div class="row">
      <div class="col-sm-7 col-sm-offset-3">
        <%= f.submit :class => "btn btn-primary" %>
        <%= link_to 'Back', :back, :class => "btn btn-default" %>
      </div>
    </div>

<% end %>

<div>
Connect Account

<br>
<br>



<% ['facebook', 'twitter', 'github', 'linkedin', 'google_oauth2'].each do |provider| %>

  <% if current_user.authorizations.pluck(:provider).include?(provider.to_s) %>
    <%= provider.to_s.titleize %> Connected
  <% else %>
      <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path('user', provider) %>
  <% end %>
<br/>
<% end %>

</div>

app/views/users/edit.html.erb
<div class="mydata">
  <div class="container">
    <p class="lead text-center">Edycja użytkownika</p>

    <%= render 'form' %>

	<%= link_to 'Show', @user %>

  </div>
</div>

app/views/users/index.html.erb
<div class="mydata">
  <div class="container">
    <p class="lead text-center">Lista użytkowników</p>

      <table>
        <thead>
          <tr>
            <th class="col-sm-2">Name</th>
            <th class="col-sm-2">Email</th>
            <th class="col-sm-2"> </th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td>
                <%= link_to 'Show', user %>
                <%= link_to 'Edit', edit_user_path(user) %>
                <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New User', new_user_path, 
                :class => "btn btn-primary glyphicon glyphicon-star-empty pull-right" %>

  </div>
</div>

app/views/users/new.html.erb
<div class="mydata">
  <div class="container">
    <p class="lead text-center">Nowy użytkownik</p>

    <%= render 'form' %>

  </div>
</div>

app/views/users/shared/_links.erb
<%- if devise_mapping.omniauthable? %>
	<ul class="list-inline center">
	<p>Możesz zalogować się także przez: </p>

  <%- resource_class.omniauth_providers.each do |provider| %>


		<% case provider.to_s %>
		<% when 'facebook' %>
	    <li><%= link_to image_tag("Facebook.png", height: '32', width: '32'), omniauth_authorize_path(resource_name, provider), title: 'Facebook', rel: 'tooltip'  %></li>
		<% when 'twitter' %>
	    <li><%= link_to image_tag("Twitter.png", height: '32', width: '32'), omniauth_authorize_path(resource_name, provider), title: 'Twitter', rel: 'tooltip'  %></li>
		<% when 'linkedin' %>
	    <li><%= link_to image_tag("Linkedin.png", height: '32', width: '32'), omniauth_authorize_path(resource_name, provider), title: 'Linkedin', rel: 'tooltip'  %></li>
		<% when 'github' %>
	    <li><%= link_to image_tag("Github.png", height: '32', width: '32'), omniauth_authorize_path(resource_name, provider), title: 'GitHub', rel: 'tooltip'  %></li>
		<% when 'passthru' %>
	    <li><%= link_to "P #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %></li>
		<% when 'google_oauth2' %>
	    <li><%= link_to image_tag("Google+.png", height: '32', width: '32'), omniauth_authorize_path(resource_name, provider), title: 'Google+', rel: 'tooltip'  %></li>
		<% else %>
	    <li><%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %></li>
		<% end %>


  <% end -%>
  </ul>
<% end -%>

<!--
	alias_method :facebook, :all
	alias_method :twitter, :all
	alias_method :linkedin, :all
	alias_method :github, :all
	alias_method :passthru, :all
	alias_method :google_oauth2, :all
-->

<br>

<%- if controller_name != 'sessions' %>
  <%= link_to "Zaloguj się", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Zarejestruj się", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Zapomniałeś hasła?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

app/views/users/show.html.erb
<div class="mydata">
  <div class="container">
    <p class="lead text-center">Edycja użytkownika</p>

	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Name:</strong>
	  <%= @user.name %>
	</p>

	<p>
	  <strong>Email:</strong>
	  <%= @user.email %>
	</p>

	<%= link_to 'Edit', edit_user_path(@user) %>


  </div>
</div>